// packages/menu-vue/src/components/UiMenu.vue
<script setup lang="ts">
import type { MenuCallbacks, MenuOptions } from "@affino/menu-core"
import { provideMenuProvider } from "../context"
import { useMenuController } from "../useMenuController"

const props = defineProps<{ options?: MenuOptions; callbacks?: MenuCallbacks }>()

const controller = useMenuController({ kind: "root", options: props.options, callbacks: props.callbacks })

const provider = provideMenuProvider({ controller })

defineExpose({ controller })
</script>

<template>
  <div class="ui-menu">
    <slot />
  </div>
</template>

// packages/menu-react/src/components/UiMenu.tsx
import type { PropsWithChildren } from "react"
import type { MenuCallbacks, MenuOptions } from "@affino/menu-core"
import { MenuProvider, useMenuProviderValue } from "../context"
import { useMenuController } from "../useMenuController"

interface UiMenuProps extends PropsWithChildren {
  options?: MenuOptions
  callbacks?: MenuCallbacks
}

export function UiMenu({ options, callbacks, children }: UiMenuProps) {
  const controller = useMenuController({ kind: "root", options, callbacks })
  const provider = useMenuProviderValue({ controller })
  return (
    <MenuProvider value={provider}>
      <div className="ui-menu">{children}</div>
    </MenuProvider>
  )
}
