// packages/menu-vue/src/components/UiMenuBaseTrigger.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue"
import type { ComponentPublicInstance, ComputedRef } from "vue"
import type { ItemProps, TriggerProps } from "@affino/menu-core"
import type { MenuController } from "../useMenuController"
import type { MenuProviderValue, SubmenuProviderValue } from "../context"
import AsChildRenderer from "../useAsChild"
import { useMenuPointerHandlers } from "../useMenuPointerHandlers"
import { useSubmenuBridge } from "../useSubmenuBridge"

const stopPropagationKeys = new Set(["ArrowDown", "ArrowUp", "ArrowLeft", "ArrowRight", "Home", "End", "Enter", " ", "Space"])
const LONG_PRESS_DELAY_MS = 450
const LONG_PRESS_MOVE_TOLERANCE_PX = 12

type TriggerMode = "click" | "contextmenu" | "both"

const props = defineProps<{
  provider: MenuProviderValue
  variant: "menu" | "submenu"
  asChild?: boolean
  triggerMode?: TriggerMode
  showArrow?: boolean
  componentLabel: string
}>()

const el = ref<HTMLElement | null>(null)
const triggerMode = computed<TriggerMode>(() => {
  if (props.triggerMode) return props.triggerMode
  return props.variant === "menu" ? "click" : "both"
})
const openOnClick = computed(() => triggerMode.value === "click" || triggerMode.value === "both")
const openOnContext = computed(() => triggerMode.value === "contextmenu" || triggerMode.value === "both")

const submenuBridge = useSubmenuBridge(props.variant)
const targetController = submenuBridge ? submenuBridge.child.controller : props.provider.controller
const parentController = submenuBridge?.parent.controller ?? props.provider.parentController
const submenuItemId = submenuBridge?.child.submenuItemId ?? props.provider.submenuItemId ?? null

const triggerBindings = computed(() => targetController.core.getTriggerProps())
const parentBindings = computed(() => {
  if (props.variant !== "submenu" || !parentController || !submenuItemId) {
    return null
  }
  void parentController.state.value
  return parentController.core.getItemProps(submenuItemId)
})

const pointerHandlers = useMenuPointerHandlers(props.provider)
const triggerPointer = pointerHandlers.makeTriggerHandlers({ bindings: triggerBindings, bridge: submenuBridge })
const disposeSubmenuLifecycle = setupSubmenuLifecycle({
  isSubmenu: props.variant === "submenu",
  parentController,
  submenuItemId,
  triggerRef: el,
})

function bind(element: Element | ComponentPublicInstance | null) {
  const target = resolveElement(element)
  el.value = target
  props.provider.controller.triggerRef.value = target
}

onBeforeUnmount(() => {
  disposeSubmenuLifecycle()
  if (props.provider.controller.triggerRef.value === el.value) {
    props.provider.controller.triggerRef.value = null
  }
})

const elementBindings = computed(() => createElementBindings(props.variant, triggerBindings, parentBindings))
const eventHandlers = createTriggerEventHandlers({
  variant: props.variant,
  provider: props.provider,
  targetController,
  triggerBindings,
  parentBindings,
  pointer: triggerPointer,
  openOnClick,
  openOnContext,
  submenuBridge,
})

const triggerProps = computed(() => ({
  class: props.variant === "submenu" ? "ui-submenu-trigger" : "ui-menu-trigger",
  id: elementBindings.value.id,
  role: elementBindings.value.role,
  tabindex: elementBindings.value.tabIndex,
  "data-state": elementBindings.value.dataState,
  "aria-disabled": elementBindings.value.ariaDisabled,
  "aria-haspopup": elementBindings.value.ariaHaspopup,
  "aria-expanded": elementBindings.value.ariaExpanded,
  "aria-controls": elementBindings.value.ariaControls,
  "data-ui-menu-trigger": "true",
  "data-ui-menu-id": targetController.id,
  "data-ui-root-menu-id": props.provider.rootId,
  "data-ui-parent-menu-id": parentController?.id ?? null,
  onPointerenter: props.variant === "submenu" ? eventHandlers.handlePointerEnter : undefined,
  onPointerleave: props.variant === "submenu" ? eventHandlers.handlePointerLeave : undefined,
  onPointerdown: props.variant === "menu" ? eventHandlers.handlePointerDown : undefined,
  onPointerup: props.variant === "menu" ? eventHandlers.handlePointerUp : undefined,
  onPointercancel: props.variant === "menu" ? eventHandlers.handlePointerCancel : undefined,
  onPointermove: props.variant === "menu" ? eventHandlers.handlePointerMove : undefined,
  onClick: props.variant === "menu" ? (openOnClick.value ? eventHandlers.handleClick : undefined) : eventHandlers.handleClick,
  onContextmenu: props.variant === "menu" ? (openOnContext.value ? eventHandlers.handleContextMenu : undefined) : undefined,
  onKeydown: eventHandlers.handleKeydown,
}))

const asChildBindings = computed(() => {
  const { class: _class, ...rest } = triggerProps.value
  return {
    ...rest,
    ref: bind,
  }
})

interface TriggerPointerHandlers {
  onPointerEnter: (event: PointerEvent) => void
  onPointerLeave: (event: PointerEvent) => void
}

function resolveElement(element: Element | ComponentPublicInstance | null) {
  if (!element) return null
  if (element instanceof HTMLElement) return element
  if ((element as ComponentPublicInstance | null)?.$el instanceof HTMLElement) {
    return (element as ComponentPublicInstance).$el as HTMLElement
  }
  return null
}

function setupSubmenuLifecycle(options: {
  isSubmenu: boolean
  parentController: MenuController | null
  submenuItemId: string | null
  triggerRef: typeof el
}) {
  if (!options.isSubmenu || !options.parentController || !options.submenuItemId) {
    return () => {}
  }

  const unregister = options.parentController.core.registerItem(options.submenuItemId)
  const stopWatch = watch(
    () => options.parentController?.state.value.activeItemId,
    (activeId) => {
      if (activeId === options.submenuItemId) {
        options.triggerRef.value?.focus({ preventScroll: true })
      }
    },
    { flush: "sync" }
  )

  return () => {
    unregister?.()
    stopWatch()
  }
}

function createElementBindings(
  variant: "menu" | "submenu",
  triggerBindings: ComputedRef<TriggerProps>,
  parentBindings: ComputedRef<ItemProps | null>
) {
  const base = triggerBindings.value
  if (variant !== "submenu" || !parentBindings.value) {
    return {
      id: base.id,
      role: base.role,
      tabIndex: base.tabIndex,
      dataState: undefined,
      ariaDisabled: undefined,
      ariaHaspopup: base["aria-haspopup"],
      ariaExpanded: base["aria-expanded"],
      ariaControls: base["aria-controls"],
    }
  }

  return {
    id: parentBindings.value.id,
    role: parentBindings.value.role,
    tabIndex: parentBindings.value.tabIndex,
    dataState: parentBindings.value["data-state"],
    ariaDisabled: parentBindings.value["aria-disabled"],
    ariaHaspopup: base["aria-haspopup"],
    ariaExpanded: base["aria-expanded"],
    ariaControls: base["aria-controls"],
  }
}

function createTriggerEventHandlers(options: {
  variant: "menu" | "submenu"
  provider: MenuProviderValue
  targetController: MenuController
  triggerBindings: ComputedRef<TriggerProps>
  parentBindings: ComputedRef<ItemProps | null>
  pointer: TriggerPointerHandlers
  openOnClick: ComputedRef<boolean>
  openOnContext: ComputedRef<boolean>
  submenuBridge: SubmenuProviderValue | null
}) {
  const ancestorBridge = options.submenuBridge?.parentSubmenu ?? null
  let longPressTimer: ReturnType<typeof setTimeout> | null = null
  let longPressOrigin: { x: number; y: number } | null = null

  const resetAnchor = () => options.provider.controller.setAnchor(null)
  const setAnchorFromEvent = (event: MouseEvent) => {
    options.provider.controller.setAnchor({ x: event.clientX, y: event.clientY, width: 0, height: 0 })
  }

  const shouldHandleLongPress = (event: PointerEvent) =>
    options.variant === "menu" && options.openOnContext.value && event.pointerType === "touch"

  const clearLongPress = () => {
    if (longPressTimer) {
      clearTimeout(longPressTimer)
      longPressTimer = null
    }
    longPressOrigin = null
  }

  const scheduleLongPress = (event: PointerEvent) => {
    clearLongPress()
    longPressOrigin = { x: event.clientX, y: event.clientY }
    longPressTimer = setTimeout(() => {
      longPressTimer = null
      longPressOrigin = null
      handleContextMenu(event)
    }, LONG_PRESS_DELAY_MS)
  }

  const cancelIfPointerMoved = (event: PointerEvent) => {
    if (!longPressOrigin) return
    const dx = event.clientX - longPressOrigin.x
    const dy = event.clientY - longPressOrigin.y
    if (dx * dx + dy * dy > LONG_PRESS_MOVE_TOLERANCE_PX * LONG_PRESS_MOVE_TOLERANCE_PX) {
      clearLongPress()
    }
  }

  const handleClick = (event: MouseEvent) => {
    if (options.variant === "menu" && !options.openOnClick.value) return
    options.targetController.recordPointer?.({ x: event.clientX, y: event.clientY })
    if (options.variant === "menu") {
      resetAnchor()
    }
    options.triggerBindings.value.onClick?.(event)
  }

  const handleContextMenu = (event: MouseEvent) => {
    if (options.variant !== "menu") {
      options.targetController.recordPointer?.({ x: event.clientX, y: event.clientY })
      options.triggerBindings.value.onClick?.(event)
      return
    }
    if (!options.openOnContext.value) return
    event.preventDefault()
    if (options.provider.controller.state.value.open) {
      options.provider.controller.close("pointer")
      requestAnimationFrame(() => {
        setAnchorFromEvent(event)
        options.provider.controller.open("pointer")
      })
      return
    }
    setAnchorFromEvent(event)
    options.provider.controller.open("pointer")
  }

  const handleKeydown = (event: KeyboardEvent) => {
    if (options.variant === "menu") {
      resetAnchor()
    }

    if (
      options.variant === "submenu" &&
      event.key === "ArrowLeft" &&
      !options.targetController.state.value.open &&
      ancestorBridge
    ) {
      event.preventDefault()
      ancestorBridge.child.controller.close("keyboard")
      ancestorBridge.parent.controller.highlight(ancestorBridge.child.submenuItemId ?? null)
      ancestorBridge.child.controller.triggerRef.value?.focus({ preventScroll: true })
      return
    }

    if (stopPropagationKeys.has(event.key)) {
      event.stopPropagation()
    }

    if (options.variant === "submenu" && options.parentBindings.value) {
      options.parentBindings.value.onKeyDown?.(event)
    }

    options.triggerBindings.value.onKeyDown?.(event)
  }

  const handlePointerEnter = (event: PointerEvent) => {
    if (options.variant === "submenu" && options.parentBindings.value) {
      options.parentBindings.value.onPointerEnter?.(event)
    }
    options.pointer.onPointerEnter(event)
  }

  const handlePointerLeave = (event: PointerEvent) => {
    options.pointer.onPointerLeave(event)
  }

  const handlePointerDown = (event: PointerEvent) => {
    if (!shouldHandleLongPress(event)) {
      clearLongPress()
      return
    }
    event.preventDefault()
    scheduleLongPress(event)
  }

  const handlePointerMove = (event: PointerEvent) => {
    if (!shouldHandleLongPress(event)) return
    cancelIfPointerMoved(event)
  }

  const handlePointerUp = (event: PointerEvent) => {
    if (shouldHandleLongPress(event)) {
      cancelIfPointerMoved(event)
    }
    clearLongPress()
  }

  const handlePointerCancel = () => {
    clearLongPress()
  }

  return {
    handleClick,
    handleContextMenu,
    handleKeydown,
    handlePointerEnter,
    handlePointerLeave,
    handlePointerDown,
    handlePointerMove,
    handlePointerUp,
    handlePointerCancel,
  }
}
</script>

<template>
  <AsChildRenderer
    v-if="props.asChild"
    :component-label="props.componentLabel"
    :forwarded-props="asChildBindings"
  >
    <slot />
  </AsChildRenderer>
  <button v-else type="button" :ref="bind" v-bind="triggerProps">
    <slot />
    <span v-if="props.variant === 'submenu' || props.showArrow" class="ui-submenu-arrow">▶</span>
  </button>
</template>

// packages/menu-react/src/components/UiMenuBaseTrigger.tsx
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react"
import type {
  PropsWithChildren,
  PointerEvent as ReactPointerEvent,
  MouseEvent as ReactMouseEvent,
  KeyboardEvent as ReactKeyboardEvent,
} from "react"
import type { ItemProps, TriggerProps } from "@affino/menu-core"
import type { MenuProviderValue, SubmenuProviderValue } from "../context"
import { AsChild } from "./AsChild"
import { useMenuPointerHandlers } from "../useMenuPointerHandlers"
import { useSubmenuBridge } from "../useSubmenuBridge"
import type { MenuController } from "../useMenuController"
import { isDebugMenuEnabled } from "../debugEnv"

const stopPropagationKeys = new Set(["ArrowDown", "ArrowUp", "ArrowLeft", "ArrowRight", "Home", "End", "Enter", " ", "Space"])
const LONG_PRESS_DELAY_MS = 450
const LONG_PRESS_MOVE_TOLERANCE_PX = 12

type TriggerMode = "click" | "contextmenu" | "both"

interface TriggerPointerHandlers {
  onPointerEnter: (event: PointerEvent) => void
  onPointerLeave: (event: PointerEvent) => void
}

interface UiMenuBaseTriggerProps extends PropsWithChildren {
  provider: MenuProviderValue
  variant: "menu" | "submenu"
  asChild?: boolean
  triggerMode?: TriggerMode
  showArrow?: boolean
  componentLabel: string
}

export function UiMenuBaseTrigger({
  provider,
  variant,
  asChild,
  triggerMode,
  showArrow,
  componentLabel,
  children,
}: UiMenuBaseTriggerProps) {
  const elementRef = useRef<HTMLElement | null>(null)
  const computedMode = useMemo<TriggerMode>(() => {
    if (triggerMode) return triggerMode
    return variant === "menu" ? "click" : "both"
  }, [triggerMode, variant])

  const openOnClick = computedMode === "click" || computedMode === "both"
  const openOnContext = computedMode === "contextmenu" || computedMode === "both"

  const submenuBridge = useSubmenuBridge(variant)
  const targetController = submenuBridge ? submenuBridge.child.controller : provider.controller
  const parentController = submenuBridge?.parent.controller ?? provider.parentController
  const submenuItemId = submenuBridge?.child.submenuItemId ?? provider.submenuItemId ?? null

  const triggerBindings = targetController.core.getTriggerProps()
  const parentBindings = useMemo(() => {
    if (variant !== "submenu" || !parentController || !submenuItemId) {
      return null
    }
    return parentController.core.getItemProps(submenuItemId)
  }, [variant, parentController, submenuItemId])

  const pointerHandlers = useMenuPointerHandlers(provider)
  const triggerPointer = pointerHandlers.makeTriggerHandlers({ bindings: triggerBindings, bridge: submenuBridge })
  const [boundElement, setBoundElement] = useState<HTMLElement | null>(null)
  const setTriggerElement = provider.controller.setTriggerElement

  const bindElement = useCallback((node: HTMLElement | null) => {
    elementRef.current = node
    setBoundElement((prev) => (prev === node ? prev : node))
  }, [])

  useLayoutEffect(() => {
    setTriggerElement(boundElement)
  }, [boundElement, setTriggerElement])

  useEffect(() => {
    return () => {
      setTriggerElement(null)
    }
  }, [setTriggerElement])

  const parentCore = parentController?.core ?? null
  const parentControllerId = parentController?.id ?? null

  useEffect(() => {
    if (variant !== "submenu" || !parentCore || !submenuItemId) {
      return
    }
    if (isDebugMenuEnabled()) {
      console.log("register submenu", parentControllerId, submenuItemId)
    }
    const unregister = parentCore.registerItem(submenuItemId)
    return () => {
      if (isDebugMenuEnabled()) {
        console.log("unregister submenu", parentControllerId, submenuItemId)
      }
      unregister?.()
    }
  }, [variant, parentCore, submenuItemId, parentControllerId])

  useEffect(() => {
    if (variant !== "submenu" || !parentController || !submenuItemId) {
      return
    }
    if (parentController.state.activeItemId === submenuItemId) {
      if (isDebugMenuEnabled()) {
        console.log("submenu trigger highlighted", submenuItemId)
      }
      elementRef.current?.focus({ preventScroll: true })
    }
  }, [variant, parentController, submenuItemId, parentController?.state.activeItemId])

  const elementBindings = useMemo(() => createElementBindings(variant, triggerBindings, parentBindings), [variant, triggerBindings, parentBindings])

  const {
    handleClick,
    handleContextMenu,
    handleKeydown,
    handlePointerEnter,
    handlePointerLeave,
    handlePointerDown,
    handlePointerMove,
    handlePointerUp,
    handlePointerCancel,
  } = useTriggerEventHandlers({
    variant,
    provider,
    targetController,
    triggerBindings,
    parentBindings,
    pointer: triggerPointer,
    openOnClick,
    openOnContext,
    submenuBridge,
  })

  const reactPointerEnter = variant === "submenu"
    ? (event: ReactPointerEvent<HTMLElement>) => {
        if (isDebugMenuEnabled()) {
          console.log("react synthetic pointer enter", event.type)
        }
        handlePointerEnter(event.nativeEvent)
      }
    : undefined
  const reactPointerLeave = variant === "submenu"
    ? (event: ReactPointerEvent<HTMLElement>) => {
        if (isDebugMenuEnabled()) {
          console.log("react synthetic pointer leave", event.type)
        }
        handlePointerLeave(event.nativeEvent)
      }
    : undefined
  const reactMouseEnter = variant === "submenu"
    ? (event: ReactMouseEvent<HTMLElement>) => handlePointerEnter(event.nativeEvent)
    : undefined
  const reactMouseLeave = variant === "submenu"
    ? (event: ReactMouseEvent<HTMLElement>) => handlePointerLeave(event.nativeEvent)
    : undefined
  const reactPointerDown = variant === "menu"
    ? (event: ReactPointerEvent<HTMLElement>) => handlePointerDown(event.nativeEvent)
    : undefined
  const reactPointerUp = variant === "menu"
    ? (event: ReactPointerEvent<HTMLElement>) => handlePointerUp(event.nativeEvent)
    : undefined
  const reactPointerCancel = variant === "menu"
    ? () => handlePointerCancel()
    : undefined
  const reactPointerMove = variant === "menu"
    ? (event: ReactPointerEvent<HTMLElement>) => handlePointerMove(event.nativeEvent)
    : undefined
  const reactClick = variant === "menu"
    ? (openOnClick ? (event: ReactMouseEvent<HTMLElement>) => handleClick(event.nativeEvent) : undefined)
    : (event: ReactMouseEvent<HTMLElement>) => handleClick(event.nativeEvent)
  const reactContextMenu = variant === "menu" && openOnContext
    ? (event: ReactMouseEvent<HTMLElement>) => handleContextMenu(event.nativeEvent)
    : undefined
  const reactKeydown = (event: ReactKeyboardEvent<HTMLElement>) => {
    if (stopPropagationKeys.has(event.key)) {
      event.stopPropagation()
    }
    handleKeydown(event.nativeEvent)
  }

  const triggerProps = {
    className: variant === "submenu" ? "ui-submenu-trigger" : "ui-menu-trigger",
    id: elementBindings.id ?? undefined,
    role: elementBindings.role,
    tabIndex: elementBindings.tabIndex ?? undefined,
    "data-state": elementBindings.dataState,
    "aria-disabled": elementBindings.ariaDisabled,
    "aria-haspopup": elementBindings.ariaHaspopup,
    "aria-expanded": elementBindings.ariaExpanded,
    "aria-controls": elementBindings.ariaControls,
    "data-ui-menu-trigger": "true",
    "data-ui-menu-id": targetController.id,
    "data-ui-root-menu-id": provider.rootId,
    "data-ui-parent-menu-id": parentController?.id ?? undefined,
    onPointerEnter: reactPointerEnter,
    onPointerLeave: reactPointerLeave,
    onMouseEnter: reactMouseEnter,
    onMouseLeave: reactMouseLeave,
    onPointerDown: reactPointerDown,
    onPointerUp: reactPointerUp,
    onPointerCancel: reactPointerCancel,
    onPointerMove: reactPointerMove,
    onClick: reactClick,
    onContextMenu: reactContextMenu,
    onKeyDown: reactKeydown,
  }

  const asChildProps = {
    ...triggerProps,
    ref: bindElement,
  }

  if (asChild) {
    return (
      <AsChild componentLabel={componentLabel} forwardedProps={asChildProps}>
        {children}
      </AsChild>
    )
  }

  return (
    <button type="button" ref={bindElement} {...triggerProps}>
      {children}
      {(variant === "submenu" || showArrow) && <span className="ui-submenu-arrow">▶</span>}
    </button>
  )
}

function createElementBindings(
  variant: "menu" | "submenu",
  triggerBindings: TriggerProps,
  parentBindings: ItemProps | null
) {
  if (variant !== "submenu" || !parentBindings) {
    return {
      id: triggerBindings.id,
      role: triggerBindings.role,
      tabIndex: triggerBindings.tabIndex,
      dataState: undefined,
      ariaDisabled: undefined,
      ariaHaspopup: triggerBindings["aria-haspopup"],
      ariaExpanded: triggerBindings["aria-expanded"],
      ariaControls: triggerBindings["aria-controls"],
    }
  }

  return {
    id: parentBindings.id,
    role: parentBindings.role,
    tabIndex: parentBindings.tabIndex,
    dataState: parentBindings["data-state"],
    ariaDisabled: parentBindings["aria-disabled"],
    ariaHaspopup: triggerBindings["aria-haspopup"],
    ariaExpanded: triggerBindings["aria-expanded"],
    ariaControls: triggerBindings["aria-controls"],
  }
}

function useTriggerEventHandlers(args: {
  variant: "menu" | "submenu"
  provider: MenuProviderValue
  targetController: MenuController
  triggerBindings: TriggerProps
  parentBindings: ItemProps | null
  pointer: TriggerPointerHandlers
  openOnClick: boolean
  openOnContext: boolean
  submenuBridge: SubmenuProviderValue | null
}) {
  const ancestorBridge = args.submenuBridge?.parentSubmenu ?? null
  const longPressTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const longPressOrigin = useRef<{ x: number; y: number } | null>(null)

  const resetAnchor = () => args.provider.controller.setAnchor(null)
  const setAnchorFromEvent = (event: MouseEvent | PointerEvent) => {
    args.provider.controller.setAnchor({ x: event.clientX, y: event.clientY, width: 0, height: 0 })
  }

  const shouldHandleLongPress = (event: PointerEvent) =>
    args.variant === "menu" && args.openOnContext && event.pointerType === "touch"

  const clearLongPress = () => {
    if (longPressTimer.current) {
      clearTimeout(longPressTimer.current)
      longPressTimer.current = null
    }
    longPressOrigin.current = null
  }

  const handleContextMenu = useCallback((event: MouseEvent | PointerEvent) => {
    if (args.variant !== "menu") {
      args.targetController.recordPointer?.({ x: event.clientX, y: event.clientY })
      args.triggerBindings.onClick?.(event as MouseEvent)
      return
    }
    if (!args.openOnContext) return
    event.preventDefault()
    if (args.provider.controller.state.open) {
      args.provider.controller.close("pointer")
      requestAnimationFrame(() => {
        setAnchorFromEvent(event)
        args.provider.controller.open("pointer")
      })
      return
    }
    setAnchorFromEvent(event)
    args.provider.controller.open("pointer")
  }, [args])

  const scheduleLongPress = (event: PointerEvent) => {
    clearLongPress()
    longPressOrigin.current = { x: event.clientX, y: event.clientY }
    longPressTimer.current = setTimeout(() => {
      longPressTimer.current = null
      longPressOrigin.current = null
      handleContextMenu(event)
    }, LONG_PRESS_DELAY_MS)
  }

  const cancelIfPointerMoved = (event: PointerEvent) => {
    if (!longPressOrigin.current) return
    const dx = event.clientX - longPressOrigin.current.x
    const dy = event.clientY - longPressOrigin.current.y
    if (dx * dx + dy * dy > LONG_PRESS_MOVE_TOLERANCE_PX * LONG_PRESS_MOVE_TOLERANCE_PX) {
      clearLongPress()
    }
  }

  const handleClick = (event: MouseEvent) => {
    if (args.variant === "menu" && !args.openOnClick) return
    args.targetController.recordPointer?.({ x: event.clientX, y: event.clientY })
    if (args.variant === "menu") {
      resetAnchor()
    }
    if (isDebugMenuEnabled()) {
      console.log("ui-menu trigger click", {
        id: args.targetController.id,
        openBefore: args.targetController.state.open,
        hasCoreHandler: Boolean(args.triggerBindings.onClick),
      })
    }
    if (args.triggerBindings.onClick) {
      args.triggerBindings.onClick(event)
    } else {
      args.targetController.toggle()
    }
    if (isDebugMenuEnabled()) {
      queueMicrotask(() => {
        console.log("ui-menu trigger toggled", {
          id: args.targetController.id,
          openAfter: args.targetController.state.open,
        })
      })
    }
  }

  const handleKeydown = (event: KeyboardEvent) => {
    if (isDebugMenuEnabled()) {
      console.log("handleKeydown", args.variant, event.key, args.targetController.state.open, args.targetController.kind, args.targetController.core.constructor.name)
    }
    if (args.variant === "menu") {
      resetAnchor()
    }

    if (
      args.variant === "submenu" &&
      event.key === "ArrowLeft" &&
      !args.targetController.state.open &&
      ancestorBridge
    ) {
      event.preventDefault()
      ancestorBridge.child.controller.close("keyboard")
      ancestorBridge.parent.controller.highlight(ancestorBridge.child.submenuItemId ?? null)
      ancestorBridge.child.controller.triggerRef.current?.focus({ preventScroll: true })
      return
    }

    if (stopPropagationKeys.has(event.key)) {
      event.stopPropagation()
    }

    if (args.variant === "submenu" && args.parentBindings) {
      args.parentBindings.onKeyDown?.(event)
    }

    if (isDebugMenuEnabled()) {
      console.log(
        "hasTriggerKeydown",
        Boolean(args.triggerBindings.onKeyDown),
        args.triggerBindings.onKeyDown?.toString().slice(0, 80)
      )
    }
    args.triggerBindings.onKeyDown?.(event)
    if (isDebugMenuEnabled()) {
      console.log("after", args.targetController.state.open)
    }
  }

  const handlePointerEnter = (event: PointerEvent | MouseEvent) => {
    if (isDebugMenuEnabled()) {
      console.log("pointer enter", args.variant, args.targetController.id)
    }
    if (args.variant === "submenu" && args.parentBindings) {
      args.parentBindings.onPointerEnter?.(event)
    }
    args.pointer.onPointerEnter(event as PointerEvent)
  }

  const handlePointerLeave = (event: PointerEvent | MouseEvent) => {
    if (isDebugMenuEnabled()) {
      console.log("pointer leave", args.variant, args.targetController.id)
    }
    args.pointer.onPointerLeave(event as PointerEvent)
  }

  const handlePointerDown = (event: PointerEvent) => {
    if (!shouldHandleLongPress(event)) {
      clearLongPress()
      return
    }
    event.preventDefault()
    scheduleLongPress(event)
  }

  const handlePointerMove = (event: PointerEvent) => {
    if (!shouldHandleLongPress(event)) return
    cancelIfPointerMoved(event)
  }

  const handlePointerUp = (event: PointerEvent) => {
    if (shouldHandleLongPress(event)) {
      cancelIfPointerMoved(event)
    }
    clearLongPress()
  }

  const handlePointerCancel = () => {
    clearLongPress()
  }

  useEffect(() => {
    return () => {
      clearLongPress()
    }
  }, [])

  return {
    handleClick,
    handleContextMenu,
    handleKeydown,
    handlePointerEnter,
    handlePointerLeave,
    handlePointerDown,
    handlePointerMove,
    handlePointerUp,
    handlePointerCancel,
  }
}
