// packages/menu-vue/src/components/UiSubMenu.vue
<script setup lang="ts">
import type { MenuCallbacks, MenuOptions, SubmenuCore } from "@affino/menu-core"
import { provideMenuProvider, provideSubmenuProvider, useMenuProvider } from "../context"
import { uid } from "../id"
import { useMenuController } from "../useMenuController"
import { usePointerRecorder } from "../usePointerRecorder"

const props = defineProps<{ id?: string; options?: MenuOptions; callbacks?: MenuCallbacks }>()

const parentProvider = useMenuProvider()
const submenuItemId = props.id ?? uid("ui-submenu-item")

const controller = useMenuController({
  kind: "submenu",
  parent: parentProvider.controller,
  parentItemId: submenuItemId,
  options: props.options,
  callbacks: props.callbacks,
})

const provider = provideMenuProvider({
  controller,
  parent: parentProvider,
  submenuItemId,
})

provideSubmenuProvider({
  parent: parentProvider,
  child: provider,
})

usePointerRecorder(controller.core as SubmenuCore)

defineExpose({ controller })
</script>

<template>
  <slot />
</template>

// packages/menu-react/src/components/UiSubMenu.tsx
import { useMemo } from "react"
import type { PropsWithChildren } from "react"
import type { MenuCallbacks, MenuOptions, SubmenuCore } from "@affino/menu-core"
import { useMenuProvider, MenuProvider, useMenuProviderValue, SubmenuProvider, useSubmenuProviderValue } from "../context"
import { useMenuController } from "../useMenuController"
import { uid } from "../id"
import { usePointerRecorder } from "../usePointerRecorder"

interface UiSubMenuProps extends PropsWithChildren {
  id?: string
  options?: MenuOptions
  callbacks?: MenuCallbacks
}

export function UiSubMenu({ id, options, callbacks, children }: UiSubMenuProps) {
  const parentProvider = useMenuProvider()
  const submenuItemId = useMemo(() => id ?? uid("ui-submenu-item"), [id])
  const controller = useMenuController({
    kind: "submenu",
    parent: parentProvider.controller,
    parentItemId: submenuItemId,
    options,
    callbacks,
  })
  const childProvider = useMenuProviderValue({ controller, parent: parentProvider, submenuItemId })
  const submenuBridge = useSubmenuProviderValue({ parent: parentProvider, child: childProvider })
  usePointerRecorder(controller.core as SubmenuCore)

  return (
    <MenuProvider value={childProvider}>
      <SubmenuProvider value={submenuBridge}>{children}</SubmenuProvider>
    </MenuProvider>
  )
}
