// packages/menu-react/src/components/UiMenuTrigger.tsx
import type { PropsWithChildren } from "react"
import { useMenuProvider } from "../context"
import { UiMenuBaseTrigger } from "./UiMenuBaseTrigger"

type TriggerMode = "click" | "contextmenu" | "both"

interface UiMenuTriggerProps extends PropsWithChildren {
  asChild?: boolean
  trigger?: TriggerMode
}

export function UiMenuTrigger({ asChild, trigger, children }: UiMenuTriggerProps) {
  const provider = useMenuProvider()
  return (
    <UiMenuBaseTrigger
      provider={provider}
      variant="menu"
      asChild={asChild}
      triggerMode={trigger}
      componentLabel="UiMenuTrigger"
    >
      {children}
    </UiMenuBaseTrigger>
  )
}

// packages/menu-vue/src/components/UiMenuTrigger.vue
<script setup lang="ts">
import { useMenuProvider } from "../context"
import UiMenuBaseTrigger from "./UiMenuBaseTrigger.vue"

const props = defineProps<{ asChild?: boolean; trigger?: "click" | "contextmenu" | "both" }>()

const provider = useMenuProvider()
</script>

<template>
  <UiMenuBaseTrigger
    :provider="provider"
    variant="menu"
    :as-child="props.asChild"
    :trigger-mode="props.trigger"
    component-label="UiMenuTrigger"
  >
    <slot />
  </UiMenuBaseTrigger>
</template>
