// packages/menu-react/src/components/UiMenuItem.tsx
import { useCallback, useEffect, useMemo, useRef } from "react"
import type { PropsWithChildren, MouseEvent as ReactMouseEvent, PointerEvent as ReactPointerEvent, KeyboardEvent as ReactKeyboardEvent } from "react"
import type { MenuController } from "../useMenuController"
import { useMenuProvider, useOptionalSubmenuProvider } from "../context"
import { uid } from "../id"
import { AsChild } from "./AsChild"

const stopPropagationKeys = new Set(["ArrowDown", "ArrowUp", "Home", "End", "Enter", " ", "Space"])

interface UiMenuItemProps extends PropsWithChildren {
  id?: string
  disabled?: boolean
  danger?: boolean
  asChild?: boolean
  onSelect?: (payload: { id: string; controller: MenuController }) => void
}

export function UiMenuItem({ id, disabled, danger, asChild, onSelect, children }: UiMenuItemProps) {
  const provider = useMenuProvider()
  const submenuBridge = useOptionalSubmenuProvider()
  const itemId = useMemo(() => id ?? uid("ui-menu-item"), [id])
  const elementRef = useRef<HTMLElement | null>(null)
  const controller = provider.controller
  const core = controller.core

  useEffect(() => {
    const unregister = core.registerItem(itemId, { disabled })
    return () => {
      unregister?.()
    }
  }, [core, itemId, disabled])

  const bindings = core.getItemProps(itemId)
  const isDisabled = Boolean(bindings["aria-disabled"])

  useEffect(() => {
    if (controller.state.activeItemId === itemId && !isDisabled) {
      elementRef.current?.focus({ preventScroll: true })
    }
  }, [controller.state.activeItemId, itemId, isDisabled])

  const emitSelect = useCallback(() => {
    onSelect?.({ id: itemId, controller })
  }, [onSelect, itemId, controller])

  const handleClick = (event: ReactMouseEvent) => {
    if (isDisabled) {
      event.preventDefault()
      return
    }
    emitSelect()
    bindings.onClick?.(event.nativeEvent)
  }

  const handlePointerEnter = (event: ReactPointerEvent) => {
    bindings.onPointerEnter?.(event.nativeEvent)
  }

  const handleKeydown = (event: ReactKeyboardEvent) => {
    if (!isDisabled && (event.key === "Enter" || event.key === " " || event.key === "Space")) {
      emitSelect()
      bindings.onKeyDown?.(event.nativeEvent)
      event.preventDefault()
      return
    }
    if (submenuBridge && event.key === "ArrowLeft") {
      event.preventDefault()
      event.stopPropagation()
      submenuBridge.child.controller.close("keyboard")
      submenuBridge.parent.controller.highlight(submenuBridge.child.submenuItemId ?? null)
      submenuBridge.child.controller.triggerRef.current?.focus({ preventScroll: true })
      return
    }
    if (stopPropagationKeys.has(event.key)) {
      event.stopPropagation()
    }
    bindings.onKeyDown?.(event.nativeEvent)
  }

  const handleFocus = () => {
    elementRef.current?.scrollIntoView({ block: "nearest" })
  }

  const setElement = useCallback((node: HTMLElement | null) => {
    elementRef.current = node
  }, [])

  const itemProps = {
    className: ["ui-menu-item", danger ? "is-danger" : null].filter(Boolean).join(" ") || undefined,
    id: bindings.id ?? undefined,
    role: bindings.role,
    tabIndex: bindings.tabIndex ?? undefined,
    "data-state": bindings["data-state"],
    "aria-disabled": bindings["aria-disabled"],
    onFocus: handleFocus,
    onPointerEnter: handlePointerEnter,
    onClick: handleClick,
    onKeyDown: handleKeydown,
  }

  if (asChild) {
    return (
      <AsChild componentLabel="UiMenuItem" forwardedProps={{ ...itemProps, ref: setElement }}>
        {children}
      </AsChild>
    )
  }

  return (
    <div ref={setElement} {...itemProps}>
      {children}
    </div>
  )
}

// packages/menu-vue/src/components/UiMenuItem.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue"
import type { ComponentPublicInstance } from "vue"
import type { MenuController } from "../useMenuController"
import { useMenuProvider, useOptionalSubmenuProvider } from "../context"
import { uid } from "../id"
import AsChildRenderer from "../useAsChild"

const stopPropagationKeys = new Set(["ArrowDown", "ArrowUp", "Home", "End", "Enter", " ", "Space"])

const props = defineProps<{ id?: string; disabled?: boolean; danger?: boolean; asChild?: boolean }>()
const emit = defineEmits<{ (e: "select", payload: { id: string; controller: MenuController }): void }>()

const provider = useMenuProvider()
const submenuBridge = useOptionalSubmenuProvider()
const itemId = props.id ?? uid("ui-menu-item")
const unregister = provider.controller.core.registerItem(itemId, { disabled: props.disabled })

watch(
  () => props.disabled,
  (value) => {
    provider.controller.core.registerItem(itemId, { disabled: value })
  }
)

const bindings = computed(() => {
  void provider.controller.state.value
  return provider.controller.core.getItemProps(itemId)
})

const el = ref<HTMLElement | null>(null)

function bindElement(element: Element | ComponentPublicInstance | null) {
  const target = resolveElement(element)
  el.value = target
}

function resolveElement(element: Element | ComponentPublicInstance | null) {
  if (!element) return null
  if (element instanceof HTMLElement) return element
  if ((element as ComponentPublicInstance).$el instanceof HTMLElement) {
    return (element as ComponentPublicInstance).$el as HTMLElement
  }
  return null
}

function handleFocus() {
  el.value?.scrollIntoView({ block: "nearest" })
}

const isDisabled = computed(() => Boolean(bindings.value["aria-disabled"]))

watch(
  () => provider.controller.state.value.activeItemId,
  (activeId) => {
    if (activeId === itemId && !isDisabled.value) {
      el.value?.focus({ preventScroll: true })
    }
  },
  { flush: "sync" }
)

function emitSelect() {
  emit("select", { id: itemId, controller: provider.controller })
}

function handleClick(event: MouseEvent) {
  if (isDisabled.value) {
    event.preventDefault()
    return
  }
  emitSelect()
  bindings.value.onClick?.(event)
}

function handlePointerEnter(event: PointerEvent) {
  bindings.value.onPointerEnter?.(event)
}

function handleKeydown(event: KeyboardEvent) {
  if (!isDisabled.value && (event.key === "Enter" || event.key === " " || event.key === "Space")) {
    emitSelect()
    bindings.value.onKeyDown?.(event)
    event.preventDefault()
    return
  }
  if (submenuBridge && event.key === "ArrowLeft") {
    event.preventDefault()
    event.stopPropagation()
    submenuBridge.child.controller.close("keyboard")
    submenuBridge.parent.controller.highlight(submenuBridge.child.submenuItemId ?? null)
    submenuBridge.child.controller.triggerRef.value?.focus({ preventScroll: true })
    return
  }
  if (stopPropagationKeys.has(event.key)) {
    event.stopPropagation()
  }
  bindings.value.onKeyDown?.(event)
}

onBeforeUnmount(() => {
  unregister()
})

const itemProps = computed(() => ({
  class: ["ui-menu-item", { "is-danger": props.danger }],
  id: bindings.value.id,
  role: bindings.value.role,
  tabindex: bindings.value.tabIndex,
  "data-state": bindings.value["data-state"],
  "aria-disabled": bindings.value["aria-disabled"],
  onFocus: handleFocus,
  onPointerenter: handlePointerEnter,
  onClick: handleClick,
  onKeydown: handleKeydown,
}))

const asChildItemProps = computed(() => ({
  ...itemProps.value,
  ref: bindElement,
}))
</script>

<template>
  <AsChildRenderer
    v-if="props.asChild"
    component-label="UiMenuItem"
    :forwarded-props="asChildItemProps"
  >
    <slot />
  </AsChildRenderer>
  <div v-else :ref="bindElement" v-bind="itemProps">
    <slot />
  </div>
</template>
