// packages/menu-react/src/components/UiMenuBaseContent.tsx
import { createPortal } from "react-dom"
import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import type {
  PropsWithChildren,
  HTMLAttributes,
  PointerEvent as ReactPointerEvent,
  MouseEvent as ReactMouseEvent,
  KeyboardEvent as ReactKeyboardEvent,
} from "react"
import type { PositionResult } from "@affino/menu-core"
import type { MenuProviderValue } from "../context"
import { useMenuPointerHandlers } from "../useMenuPointerHandlers"
import { useMenuFocus } from "../useMenuFocus"
import { useMenuPositioning } from "../useMenuPositioning"
import { toRect } from "../dom"
import { useSubmenuBridge } from "../useSubmenuBridge"
import { isDebugMenuEnabled } from "../debugEnv"

const DEBUG_MENU = isDebugMenuEnabled()

interface UiMenuBaseContentProps extends PropsWithChildren<HTMLAttributes<HTMLDivElement>> {
  provider: MenuProviderValue
  variant: "menu" | "submenu"
  teleportTo?: string
  className?: string
}

export function UiMenuBaseContent({ provider, variant, teleportTo, className, children, ...rest }: UiMenuBaseContentProps) {
  const rootRef = useRef<HTMLDivElement | null>(null)
  const controller = provider.controller
  const bindings = controller.core.getPanelProps()
  const pointerHandlers = useMenuPointerHandlers(provider)
  const submenuBridge = useSubmenuBridge(variant)
  const panelPointer = pointerHandlers.makePanelHandlers({ bindings, bridge: submenuBridge })
  const { focusFirst, focusLast } = useMenuFocus(controller.panelRef)
  const [lastPlacement, setLastPlacement] = useState<PositionResult["placement"] | null>(null)
  const isOpen = controller.state.open
  useEffect(() => {
    if (DEBUG_MENU) {
      console.log("content", controller.id, variant, "isOpen", isOpen)
    }
  }, [controller.id, variant, isOpen])
  const setPanelElement = controller.setPanelElement
  const setAnchor = controller.setAnchor
  const setTriggerRect = controller.setTriggerRect
  const setPanelRect = controller.setPanelRect
  const anchorVersion = controller.versions.anchor
  const triggerVersion = controller.versions.trigger
  const panelVersion = controller.versions.panel
  const [shouldRender, setShouldRender] = useState(isOpen)
  const [panelState, setPanelState] = useState<"open" | "closed">(isOpen ? "open" : "closed")
  const resolvedSide = lastPlacement ?? (variant === "submenu" ? "right" : "bottom")
  const resolvedMotion = motionFromSide(resolvedSide)
  const defaultClassName = variant === "submenu" ? "ui-submenu-content" : "ui-menu-content"
  const mergedClassName = className ? `${defaultClassName} ${className}` : defaultClassName

  const portalTarget = useMemo(() => {
    if (typeof document === "undefined") {
      return null
    }
    if (!teleportTo) {
      return document.body
    }
    return document.querySelector<HTMLElement>(teleportTo) ?? document.body
  }, [teleportTo])

  const preferredPlacement: PositionResult["placement"] = variant === "submenu" ? "right" : "bottom"

  const syncSubmenuGeometry = useCallback(() => {
    if (variant !== "submenu" || !submenuBridge) {
      return
    }
    const triggerRect = toRect(controller.triggerRef.current)
    setTriggerRect?.(triggerRect ?? null)
    const panelRect = toRect(rootRef.current)
    setPanelRect?.(panelRect ?? null)
  }, [variant, submenuBridge, controller.triggerRef, setTriggerRect, setPanelRect])

  const updatePosition = useMenuPositioning(controller, {
    placement: preferredPlacement,
    afterUpdate: (position) => {
      setLastPlacement(position.placement)
      syncSubmenuGeometry()
    },
  })

  const refreshGeometry = useCallback(() => {
    if (!controller.state.open) {
      return
    }
    syncSubmenuGeometry()
    updatePosition()
  }, [controller.state.open, syncSubmenuGeometry, updatePosition])
  const refreshGeometryRef = useRef(refreshGeometry)
  refreshGeometryRef.current = refreshGeometry

  useEffect(() => {
    if (isOpen) {
      setShouldRender(true)
      setPanelState("closed")
      const raf = requestAnimationFrame(() => {
        setPanelState("open")
        refreshGeometryRef.current()
        if (variant === "submenu") {
          focusFirst()
        } else {
          rootRef.current?.focus({ preventScroll: true })
        }
      })
      return () => cancelAnimationFrame(raf)
    }

    setPanelElement(null)
    setAnchor(null)
    setPanelState("closed")
    setShouldRender(false)
  }, [isOpen, focusFirst, variant, setPanelElement, setAnchor])

  useEffect(() => {
    if (isOpen) {
      refreshGeometryRef.current()
    }
  }, [isOpen, anchorVersion])

  useEffect(() => {
    if (isOpen) {
      refreshGeometryRef.current()
    }
  }, [isOpen, triggerVersion, panelVersion])

  const setRoot = useCallback((node: HTMLDivElement | null) => {
    rootRef.current = node
    setPanelElement(node)
  }, [setPanelElement])

  const handlePointerEnter = (event: ReactPointerEvent | ReactMouseEvent) => {
    panelPointer.onPointerEnter(event.nativeEvent as any)
  }

  const handlePointerLeave = (event: ReactPointerEvent | ReactMouseEvent) => {
    if (variant !== "submenu") {
      return
    }
    panelPointer.onPointerLeave(event.nativeEvent as any)
  }

  const handleKeydown = (event: ReactKeyboardEvent) => {
    if (event.key === "Tab") {
      event.preventDefault()
      if (variant === "submenu") {
        event.shiftKey ? focusLast() : focusFirst()
        return
      }
      controller.close("keyboard")
      setAnchor(null)
      controller.triggerRef.current?.focus()
      return
    }
    bindings.onKeyDown?.(event.nativeEvent)
  }

  if (!shouldRender) {
    return null
  }

  const content = (
    <div
      ref={setRoot}
      className={mergedClassName}
      id={bindings.id ?? undefined}
      role="menu"
      tabIndex={-1}
      data-ui-menu-panel="true"
      data-state={panelState}
      data-side={resolvedSide}
      data-motion={resolvedMotion}
      data-ui-root-menu-id={provider.rootId}
      data-ui-menu-id={controller.id}
      data-ui-parent-menu-id={provider.parentController?.id ?? undefined}
      onPointerEnter={handlePointerEnter as any}
      onPointerLeave={handlePointerLeave as any}
      onMouseEnter={handlePointerEnter as any}
      onMouseLeave={handlePointerLeave as any}
      onKeyDown={handleKeydown as any}
      {...rest}
    >
      {children}
    </div>
  )

  if (portalTarget) {
    return createPortal(content, portalTarget)
  }

  return content
}

function motionFromSide(side: PositionResult["placement"]) {
  switch (side) {
    case "top":
      return "from-top"
    case "left":
      return "from-left"
    case "right":
      return "from-right"
    case "bottom":
    default:
      return "from-bottom"
  }
}

// packages/menu-vue/src/components/UiMenuBaseContent.vue
<script setup lang="ts">
import { Teleport, computed, nextTick, onBeforeUnmount, onMounted, ref, watch, useAttrs } from "vue"
import type { PositionResult } from "@affino/menu-core"
import type { MenuProviderValue } from "../context"
import { useMenuPointerHandlers } from "../useMenuPointerHandlers"
import { useMenuFocus } from "../useMenuFocus"
import { useMenuPositioning } from "../useMenuPositioning"
import { toRect } from "../dom"
import { useSubmenuBridge } from "../useSubmenuBridge"

const props = defineProps<{
  provider: MenuProviderValue
  variant: "menu" | "submenu"
  teleportTo?: string
  className?: string
}>()

const root = ref<HTMLElement | null>(null)
const bindings = computed(() => props.provider.controller.core.getPanelProps())
const pointerHandlers = useMenuPointerHandlers(props.provider)
const submenuBridge = useSubmenuBridge(props.variant)
const panelPointer = pointerHandlers.makePanelHandlers({ bindings, bridge: submenuBridge })
const focus = useMenuFocus(props.provider.controller.panelRef)
const lastPlacement = ref<PositionResult["placement"] | null>(null)
const isOpen = computed(() => props.provider.controller.state.value.open)
const shouldRender = ref(isOpen.value)
const panelState = ref<"open" | "closed">(isOpen.value ? "open" : "closed")
const resolvedSide = computed<PositionResult["placement"]>(() =>
  lastPlacement.value ?? (props.variant === "submenu" ? "right" : "bottom")
)
const resolvedMotion = computed(() => motionFromSide(resolvedSide.value))
defineOptions({ inheritAttrs: false })
const attrs = useAttrs()

const syncSubmenuGeometry = () => {
  if (props.variant !== "submenu" || !submenuBridge) {
    return
  }
  const triggerRect = toRect(submenuBridge.parent.controller.triggerRef.value)
  props.provider.controller.setTriggerRect?.(triggerRect ?? null)
  const panelRect = toRect(root.value)
  props.provider.controller.setPanelRect?.(panelRect ?? null)
}

const preferredPlacement: PositionResult["placement"] = props.variant === "submenu" ? "right" : "bottom"

const updatePosition = useMenuPositioning(props.provider.controller, {
  placement: preferredPlacement,
  afterUpdate: (position) => {
    lastPlacement.value = position.placement
    syncSubmenuGeometry()
  },
})

const teleportTarget = computed(() => props.teleportTo ?? "body")
const parentMenuId = props.provider.parentController?.id ?? ""

const refreshGeometry = () => {
  syncSubmenuGeometry()
  updatePosition()
}

const playOpenAnimation = () => {
  panelState.value = "closed"
  if (typeof window === "undefined") {
    panelState.value = "open"
    return
  }
  window.requestAnimationFrame(() => {
    panelState.value = "open"
  })
}

watch(
  isOpen,
  async (open) => {
    if (open) {
      shouldRender.value = true
      panelState.value = "closed"
      await nextTick()
      props.provider.controller.panelRef.value = root.value
      playOpenAnimation()
      refreshGeometry()
      if (props.variant === "submenu") {
        focus.focusFirst()
      } else {
        root.value?.focus({ preventScroll: true })
      }
    } else {
      if (props.provider.controller.panelRef.value === root.value) {
        props.provider.controller.panelRef.value = null
        props.provider.controller.setAnchor(null)
      }
      panelState.value = "closed"
      shouldRender.value = false
    }
  }
)

watch(
  () => props.provider.controller.anchorRef.value,
  () => {
    if (isOpen.value) {
      refreshGeometry()
    }
  }
)

onMounted(() => {
  if (isOpen.value) {
    refreshGeometry()
  }
})

onBeforeUnmount(() => {
  if (props.provider.controller.panelRef.value === root.value) {
    props.provider.controller.panelRef.value = null
  }
})

function handlePointerEnter(event: PointerEvent) {
  panelPointer.onPointerEnter(event)
}

function handlePointerLeave(event: PointerEvent) {
  if (props.variant !== "submenu") {
    return
  }
  panelPointer.onPointerLeave(event)
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === "Tab") {
    event.preventDefault()
    if (props.variant === "submenu") {
      event.shiftKey ? focus.focusLast() : focus.focusFirst()
      return
    }
    props.provider.controller.close("keyboard")
    props.provider.controller.setAnchor(null)
    props.provider.controller.triggerRef.value?.focus()
    return
  }
  bindings.value.onKeyDown?.(event)
}

function motionFromSide(side: PositionResult["placement"]) {
  switch (side) {
    case "top":
      return "from-top"
    case "left":
      return "from-left"
    case "right":
      return "from-right"
    case "bottom":
    default:
      return "from-bottom"
  }
}
</script>

<template>
  <Teleport :to="teleportTarget">
    <div
      v-if="shouldRender"
      ref="root"
      :class="props.className ?? (props.variant === 'submenu' ? 'ui-submenu-content' : 'ui-menu-content')"
      :id="bindings.id"
      role="menu"
      tabindex="-1"
      data-ui-menu-panel="true"
      :data-state="panelState"
      :data-side="resolvedSide"
      :data-motion="resolvedMotion"
      :data-ui-root-menu-id="props.provider.rootId"
      :data-ui-menu-id="props.provider.controller.id"
      :data-ui-parent-menu-id="parentMenuId"
      v-bind="attrs"
      @pointerenter="handlePointerEnter"
      @pointerleave="handlePointerLeave"
      @keydown="handleKeydown"
    >
      <slot />
    </div>
  </Teleport>
</template>
