// packages/menu-react/src/components/UiSubMenuTrigger.tsx
import type { PropsWithChildren } from "react"
import { useMenuProvider } from "../context"
import { UiMenuBaseTrigger } from "./UiMenuBaseTrigger"

interface UiSubMenuTriggerProps extends PropsWithChildren {
  asChild?: boolean
}

export function UiSubMenuTrigger({ asChild, children }: UiSubMenuTriggerProps) {
  const provider = useMenuProvider()
  return (
    <UiMenuBaseTrigger
      provider={provider}
      variant="submenu"
      asChild={asChild}
      componentLabel="UiSubMenuTrigger"
      showArrow
    >
      {children}
    </UiMenuBaseTrigger>
  )
}

// packages/menu-vue/src/components/UiSubMenuTrigger.vue
<script setup lang="ts">
import { useMenuProvider } from "../context"
import UiMenuBaseTrigger from "./UiMenuBaseTrigger.vue"

const props = defineProps<{ asChild?: boolean }>()
const provider = useMenuProvider()
</script>

<template>
  <UiMenuBaseTrigger
    :provider="provider"
    variant="submenu"
    :as-child="props.asChild"
    component-label="UiSubMenuTrigger"
    show-arrow
  >
    <slot />
  </UiMenuBaseTrigger>
</template>
